import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AdminRegistration extends StatefulWidget {
  const AdminRegistration({super.key});

  @override
  State<AdminRegistration> createState() => _AdminRegistrationState();
}

class _AdminRegistrationState extends State<AdminRegistration> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  bool _obscurePassword = true;
  bool _isLoading = false; // 🔄 Added loading state

  final supabase = Supabase.instance.client;

  // 🔐 Validations
  String? validatePassword(String? value) {
    if (value == null || value.isEmpty) return "Password is required";
    if (value.length < 8) return "Min. 8 characters required";
    if (!RegExp(r'[A-Z]').hasMatch(value)) return "Need one uppercase letter";
    if (!RegExp(r'[0-9]').hasMatch(value)) return "Need one number";
    return null;
  }

  String? validateEmail(String? value) {
    if (value == null || value.isEmpty) return "Email is required";
    if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w]{2,4}$').hasMatch(value)) return "Invalid email format";
    return null;
  }

  String? validateName(String? value) {
    if (value == null || value.trim().isEmpty) return "Full name is required";
    return null;
  }

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  // 🌿 Fixed Insert function
  Future<void> _handleRegistration() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    final name = _nameController.text.trim();
    final email = _emailController.text.trim();
    final password = _passwordController.text;

    try {
      // 1. Create User in Supabase Auth first
      final AuthResponse res = await supabase.auth.signUp(
        email: email,
        password: password,
      );

      // 2. Insert into your custom admin table using the new User ID
      if (res.user != null) {
        await supabase.from('tbl_admin').insert({
          'admin_id': res.user!.id, // Uses the ID generated by Auth
          'admin_name': name,
          'admin_email': email,
          'admin_password': password, // Consider hashing for extra security
        });

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Admin registered successfully!'), backgroundColor: Colors.green),
          );
          Navigator.pop(context); // Go back to Login
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Registration Failed: ${e.toString()}'), backgroundColor: Colors.redAccent),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          // 🖼️ Background Image (Matching Login Page)
          SizedBox.expand(
            child: Image.asset(
              'assets/bgl.png',
              fit: BoxFit.cover,
              errorBuilder: (context, error, stackTrace) => Container(color: Colors.black),
            ),
          ),

          // 🌑 Dark Overlay
          Container(color: Colors.black.withOpacity(0.8)),

          // 📋 Form Content
          SafeArea(
            child: Center(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 25),
                child: Column(
                  children: [
                    const Icon(Icons.admin_panel_settings_outlined, size: 70, color: Colors.greenAccent),
                    const SizedBox(height: 15),
                    const Text(
                      "ADMIN REGISTRATION",
                      style: TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 30),

                    // 🔹 Glassmorphic Card
                    Container(
                      padding: const EdgeInsets.all(25),
                      decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.05),
                        borderRadius: BorderRadius.circular(30),
                        border: Border.all(color: Colors.white.withOpacity(0.1)),
                      ),
                      child: Form(
                        key: _formKey,
                        child: Column(
                          children: [
                            _buildRegField(_nameController, "Full Name", Icons.person, validateName),
                            const SizedBox(height: 15),
                            _buildRegField(_emailController, "Email Address", Icons.email, validateEmail),
                            const SizedBox(height: 15),
                            
                            // Password Field
                            TextFormField(
                              controller: _passwordController,
                              obscureText: _obscurePassword,
                              validator: validatePassword,
                              style: const TextStyle(color: Colors.white),
                              decoration: _buildInputDecoration("Password", Icons.lock).copyWith(
                                suffixIcon: IconButton(
                                  icon: Icon(_obscurePassword ? Icons.visibility_off : Icons.visibility, color: Colors.white38),
                                  onPressed: () => setState(() => _obscurePassword = !_obscurePassword),
                                ),
                              ),
                            ),

                            const SizedBox(height: 30),

                            // Register Button
                            _isLoading 
                              ? const CircularProgressIndicator(color: Colors.greenAccent)
                              : SizedBox(
                                  width: double.infinity,
                                  height: 55,
                                  child: ElevatedButton(
                                    onPressed: _handleRegistration,
                                    style: ElevatedButton.styleFrom(
                                      backgroundColor: Colors.greenAccent,
                                      foregroundColor: Colors.black,
                                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(30)),
                                    ),
                                    child: const Text("CREATE ACCOUNT", style: TextStyle(fontWeight: FontWeight.bold)),
                                  ),
                                ),
                          ],
                        ),
                      ),
                    ),
                    
                    TextButton(
                      onPressed: () => Navigator.pop(context),
                      child: const Text("Already an Admin? Login", style: TextStyle(color: Colors.white60)),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  // 🛠️ Helper UI Builders
  Widget _buildRegField(TextEditingController ctrl, String hint, IconData icon, String? Function(String?)? validator) {
    return TextFormField(
      controller: ctrl,
      validator: validator,
      style: const TextStyle(color: Colors.white),
      decoration: _buildInputDecoration(hint, icon),
    );
  }

  InputDecoration _buildInputDecoration(String hint, IconData icon) {
    return InputDecoration(
      hintText: hint,
      hintStyle: const TextStyle(color: Colors.white30, fontSize: 14),
      filled: true,
      fillColor: Colors.black.withOpacity(0.4),
      prefixIcon: Icon(icon, color: Colors.greenAccent, size: 20),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(20), borderSide: BorderSide.none),
      contentPadding: const EdgeInsets.symmetric(vertical: 18),
    );
  }
}